### ISSUE TITLE
ember-model-validator does not show anything

### ISSUE THREAD

**Issue by datasc123** [esbanarango/ember-model-validator#38]
In the model I did like this:
```
import Ember from 'ember';

import Validator from 'ember-model-validator/mixins/model-validator';

export default Model.extend(Validator,{
  login: attr(),
  
  password: attr(),
  
 validations: {
    login: {
       presence: true
    },  
   password: {
     presence: true     
   }
  },

});
```
In the template.hbs I do something like this:

```
        <table>
             <tbody>
                 <tr>               
                    <td>{{input value=login}}</td>         
                    <td>{{input value=password}}</td>       
                </tr>
             </tbody>
         </table>

```

It does not show anything when I try to submit empty login or password.

Do I need to do something else ?

**Comment by dmuneras** [comment]
Hi @datasc123 

Ember model validator is going to add the errors to the ember model, but you have to print them in your template. 


So, in order to do that you have to add a button which call a function in your `route` or `controller` and that function have to do something like the function in the README:

````js

import Ember from 'ember';

export default Ember.Route.extend(
  {
    actions: {
      saveFakeModel: function() {
        var _this = this,
            fakeModel = this.get('model');

        if(fakeModel.validate()){
          fakeModel.save().then(
            // Success
            function() {
              // Alert success
              console.log('ooooh yeah we just saved the FakeModel...');
            },

            // Error handling
            function(error) {
              // Alert failure
              console.log('There was a problem saving the FakeModel...');
              console.log(error);
            }
          );
        }else{
          fakeModel.get('errors');
        }
      },
    }
  }
); 
````

In that example, the `validate()` method is going to add errors to the `fakeModel`, but, in order to show the errors you have to use the `errors` attr of the `fakeModel` in the template.

You have many options to print the errors in your template. The most basic way to do it is documented here: http://emberjs.com/api/data/classes/DS.Errors.html

Example from the document:

```hbs

<label>Username: {{input value=username}} </label>
{{#each model.errors.username as |error|}}
  <div class="error">
    {{error.message}}
  </div>
{{/each}}

<label>Email: {{input value=email}} </label>
{{#each model.errors.email as |error|}}
  <div class="error">
    {{error.message}}
  </div>
{{/each}}

```


ADDITIONAL COMMENT
--------------------

I don't know how you are setting the model in your template, but it looks wrong in the example you shared.  Could you share the route.js for that template?


Regards,
Daniel.
